//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAndLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrinho
    {
        public int PacoteID { get; set; }
        public int CompraID { get; set; }
        public System.DateTime DataIda { get; set; }
        public System.DateTime DataVolta { get; set; }
        public int Quantidade { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Pacote Pacote { get; set; }
    }
}
