//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAndLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.Carrinhoes = new HashSet<Carrinho>();
        }
    
        public int Id { get; set; }
        public Nullable<int> vezesPagamento { get; set; }
        public Nullable<int> PagamentoID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> PrecoTotal { get; set; }
        public string TipoPagamento { get; set; }
    
        public virtual Pagamento Pagamento { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrinho> Carrinhoes { get; set; }
    }
}
