//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAndLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Password { get; set; }
        public bool IsEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public string Estado { get; set; }
        public string Cidade { get; set; }
        public string Renda { get; set; }
        public string Dependentes { get; set; }
        public string Telefone { get; set; }
        public string CEP { get; set; }
        public string Endereço { get; set; }
        public string Numero { get; set; }
    }
}
